version: "3"

services:
  mongo:
    image: mongo:4.2.8
    volumes:
      - db_data:/data/db
    restart: always
    ports:
      - 27018:27017
  redis:
    image: redis
    container_name: redis
    expose:
     - "6379:6379"

  server:
    build:
      context: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    restart: always
    environment:
      SERVER_IP: ${SERVER_IP}
      SERVER_PORT: ${SERVER_PORT}
      MONGODB_IP: mongo
      MONGODB_PORT: 27017
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      NODE_ENV: production
    volumes:
      - ./folder:/app/folder/

volumes:
  db_data:

